---
# task file for general_software

# needs to improved for redundancy, use regex with lineinfile
# copy warning message before editing the config
# notify restart_sshd_service after editing the config --> it makes sense!!

- name: copy message of the day
  become: yes
  become_method: sudo
  copy:
          dest: /etc/motd
          #src: {{ role_path }}/files/motd
          src: motd
          owner: root
          group: root
          mode: u=rw,g=r,o=r

- name: enable login banner in sshd_config
  become: yes
  become_method: sudo
  lineinfile:
          dest: /etc/ssh/sshd_config
          line: "Banner /etc/login.warn"
          state: present

- name: copy warning message
  become: yes
  become_method: sudo
  copy:
          dest: /etc/login.warn
          src: login.warn
          owner: root
          group: root
          mode: u=rw,g=r,o=r
  notify:
           - restart_sshd_service

