---
# tasks file for general_software

- name: install general software
  become: yes
  action: >
          {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
          - vim
          - aptitude
          - ccze
          - htop
          - lolcat
          - bash-completion
          - autossh
          - mtr
          - dnsutils
          - cmatrix
          - speedtest-cli
          - screen
          - tree
          - figlet
          - wavemon
          - netdiscover
          - sqlite3
          - iftop
          - telnet
          - iptables
          - iptables-persistent
          - netfilter-persistent
