---
# tasks file for general_software

- name: iptables | Allow new incoming SYN packets on TCP port 22 (SSH)
  become: yes
  become_user: root
  iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept new SSH connections.

- name: iptables | save configuration to /etc/iptables/rules.v4
  become: yes
  become_user: root
  shell: iptables-save > /etc/iptables/rules.v4

- name: iptables | save configuration to /etc/iptables/rules.v6
  become: yes
  become_user: root
  shell: ip6tables-save > /etc/iptables/rules.v6
